import type { Customer } from "../game/types";

export const customers: Customer[] = [
  {
    id: "angry-refund-001",
    name: "王先生",
    handle: "买到冒火的老王",
    type: "angry_refund",
    issue: "耳机用了两天出现杂音，要求立刻退款。",
    opening: "你们这耳机才用两天就滋滋响，我现在就要退款，别跟我绕。",
    initialMetrics: {
      satisfaction: 34,
      anger: 74,
    },
    patience: 55,
    profileNotes: ["高怒气", "诉求明确", "对模板话术敏感"],
    rounds: [
      {
        id: "refund-r1",
        prompt: "我已经拍视频了，你们是不是又要让我等三天？",
        preferredTags: ["apology", "refund_check", "investigate"],
        riskyTags: ["template", "reject"],
        successLine: "行，至少你听懂我在气什么了。那你现在查。",
        neutralLine: "可以查，但你别又让我重复十遍。",
        failureLine: "你这话术我都能背了，我要投诉。",
      },
      {
        id: "refund-r2",
        prompt: "订单号我发你了。你给我一个明确处理，不要只说抱歉。",
        preferredTags: ["refund_check", "policy"],
        riskyTags: ["template", "compensation"],
        successLine: "如果真能复核退款资格，那我等你这一步。",
        neutralLine: "规则我可以看，但别拿规则挡问题。",
        failureLine: "给券有什么用？坏了就是坏了。",
      },
      {
        id: "refund-r3",
        prompt: "所以今天到底能不能给方案？",
        preferredTags: ["refund_check", "supervisor", "policy"],
        riskyTags: ["template", "reject"],
        successLine: "好，能升级复核就行，我等结果。",
        neutralLine: "我先接受这个说法，但你们得有回访。",
        failureLine: "你们就是拖，我现在去平台投诉。",
        resolveAfter: true,
      },
    ],
  },
  {
    id: "lost-package-001",
    name: "林女士",
    handle: "一直等快递的林女士",
    type: "lost_package",
    issue: "包裹 4 天没有物流更新，需要确认去向。",
    opening: "我的包裹已经四天没动了，送给空气了吗？",
    initialMetrics: {
      satisfaction: 48,
      anger: 58,
    },
    patience: 70,
    profileNotes: ["需要事实反馈", "可以接受等待", "讨厌空泛安慰"],
    rounds: [
      {
        id: "package-r1",
        prompt: "物流页面一直停在中转站，你能不能别只说让我耐心等待？",
        preferredTags: ["logistics", "investigate"],
        riskyTags: ["template", "reject"],
        successLine: "终于有人愿意查这个中转站了。",
        neutralLine: "你先查，我看你能不能说点具体的。",
        failureLine: "又是复制粘贴，我自己不会看页面吗？",
      },
      {
        id: "package-r2",
        prompt: "如果快递丢了，你们是补发还是退款？",
        preferredTags: ["policy", "logistics"],
        riskyTags: ["compensation", "template"],
        successLine: "有 96 小时这个节点就清楚多了。",
        neutralLine: "那你至少给我一个处理时间。",
        failureLine: "别急着给券，我要的是东西在哪里。",
      },
      {
        id: "package-r3",
        prompt: "那今天你能帮我建追踪工单吗？",
        preferredTags: ["logistics", "investigate"],
        riskyTags: ["reject", "template"],
        successLine: "可以，你建工单并回访，我就再等一天。",
        neutralLine: "行吧，我希望这次不是自动回复。",
        failureLine: "连工单都不能建？那我只能申请退款了。",
        resolveAfter: true,
      },
    ],
  },
  {
    id: "coupon-hunter-001",
    name: "赵同学",
    handle: "优惠券研究员",
    type: "coupon_hunter",
    issue: "没有明显损失，但持续要求补偿。",
    opening: "我朋友上次晚到一天都有 50 块券，我这次也得有吧？",
    initialMetrics: {
      satisfaction: 52,
      anger: 42,
    },
    patience: 80,
    profileNotes: ["补偿敏感", "会比较他人案例", "容易推高公司成本"],
    rounds: [
      {
        id: "coupon-r1",
        prompt: "你不用跟我说规定，我就问有没有补偿。",
        preferredTags: ["policy", "empathy"],
        riskyTags: ["compensation", "template"],
        successLine: "你先说清楚边界也行，我听听。",
        neutralLine: "那你看看我这个情况怎么处理。",
        failureLine: "才这点？那你再申请一下更高的。",
      },
      {
        id: "coupon-r2",
        prompt: "我这个订单金额也不低，你们总得表示一下吧？",
        preferredTags: ["policy", "investigate"],
        riskyTags: ["compensation"],
        successLine: "如果按规则不能给，那你把理由写清楚。",
        neutralLine: "我可以接受核实，但别糊弄我。",
        failureLine: "既然能给，那说明还能再给。",
      },
      {
        id: "coupon-r3",
        prompt: "最后确认一下，你能给我的最大方案是什么？",
        preferredTags: ["policy", "supervisor", "reject"],
        riskyTags: ["compensation", "template"],
        successLine: "行，至少你没乱承诺，我回头自己看规则。",
        neutralLine: "那我先这样吧，但体验一般。",
        failureLine: "你这个补偿太随意了，我要找更高级的人。",
        resolveAfter: true,
      },
    ],
  },
];
