import type { Customer } from "../game/types";

export const customers: Customer[] = [
  {
    id: "angry-refund-001",
    name: "王先生",
    handle: "买到冒火的老王",
    type: "angry_refund",
    issue: "耳机用了两天出现杂音，要求立刻退款。",
    opening: "你们这耳机才用两天就滋滋响，我现在就要退款，别跟我绕。",
    initialMetrics: {
      satisfaction: 34,
      anger: 74,
    },
    patience: 55,
    profileNotes: ["高怒气", "诉求明确", "对模板话术敏感"],
    rounds: [
      {
        id: "refund-r1",
        prompt: "我已经拍视频了，你们是不是又要让我等三天？",
        preferredTags: ["apology", "refund_check", "investigate"],
        riskyTags: ["template", "reject"],
        successLine: "行，至少你听懂我在气什么了。那你现在查。",
        neutralLine: "可以查，但你别又让我重复十遍。",
        failureLine: "你这话术我都能背了，我要投诉。",
      },
      {
        id: "refund-r2",
        prompt: "订单号我发你了。你给我一个明确处理，不要只说抱歉。",
        preferredTags: ["refund_check", "policy"],
        riskyTags: ["template", "compensation"],
        successLine: "如果真能复核退款资格，那我等你这一步。",
        neutralLine: "规则我可以看，但别拿规则挡问题。",
        failureLine: "给券有什么用？坏了就是坏了。",
      },
      {
        id: "refund-r3",
        prompt: "所以今天到底能不能给方案？",
        preferredTags: ["refund_check", "supervisor", "policy"],
        riskyTags: ["template", "reject"],
        successLine: "好，能升级复核就行，我等结果。",
        neutralLine: "我先接受这个说法，但你们得有回访。",
        failureLine: "你们就是拖，我现在去平台投诉。",
        resolveAfter: true,
      },
    ],
  },
  {
    id: "lost-package-001",
    name: "林女士",
    handle: "一直等快递的林女士",
    type: "lost_package",
    issue: "包裹 4 天没有物流更新，需要确认去向。",
    opening: "我的包裹已经四天没动了，送给空气了吗？",
    initialMetrics: {
      satisfaction: 48,
      anger: 58,
    },
    patience: 70,
    profileNotes: ["需要事实反馈", "可以接受等待", "讨厌空泛安慰"],
    rounds: [
      {
        id: "package-r1",
        prompt: "物流页面一直停在中转站，你能不能别只说让我耐心等待？",
        preferredTags: ["logistics", "investigate"],
        riskyTags: ["template", "reject"],
        successLine: "终于有人愿意查这个中转站了。",
        neutralLine: "你先查，我看你能不能说点具体的。",
        failureLine: "又是复制粘贴，我自己不会看页面吗？",
      },
      {
        id: "package-r2",
        prompt: "如果快递丢了，你们是补发还是退款？",
        preferredTags: ["policy", "logistics"],
        riskyTags: ["compensation", "template"],
        successLine: "有 96 小时这个节点就清楚多了。",
        neutralLine: "那你至少给我一个处理时间。",
        failureLine: "别急着给券，我要的是东西在哪里。",
      },
      {
        id: "package-r3",
        prompt: "那今天你能帮我建追踪工单吗？",
        preferredTags: ["logistics", "investigate"],
        riskyTags: ["reject", "template"],
        successLine: "可以，你建工单并回访，我就再等一天。",
        neutralLine: "行吧，我希望这次不是自动回复。",
        failureLine: "连工单都不能建？那我只能申请退款了。",
        resolveAfter: true,
      },
    ],
  },
  {
    id: "coupon-hunter-001",
    name: "赵同学",
    handle: "优惠券研究员",
    type: "coupon_hunter",
    issue: "没有明显损失，但持续要求补偿。",
    opening: "我朋友上次晚到一天都有 50 块券，我这次也得有吧？",
    initialMetrics: {
      satisfaction: 52,
      anger: 42,
    },
    patience: 80,
    profileNotes: ["补偿敏感", "会比较他人案例", "容易推高公司成本"],
    rounds: [
      {
        id: "coupon-r1",
        prompt: "你不用跟我说规定，我就问有没有补偿。",
        preferredTags: ["policy", "empathy"],
        riskyTags: ["compensation", "template"],
        successLine: "你先说清楚边界也行，我听听。",
        neutralLine: "那你看看我这个情况怎么处理。",
        failureLine: "才这点？那你再申请一下更高的。",
      },
      {
        id: "coupon-r2",
        prompt: "我这个订单金额也不低，你们总得表示一下吧？",
        preferredTags: ["policy", "investigate"],
        riskyTags: ["compensation"],
        successLine: "如果按规则不能给，那你把理由写清楚。",
        neutralLine: "我可以接受核实，但别糊弄我。",
        failureLine: "既然能给，那说明还能再给。",
      },
      {
        id: "coupon-r3",
        prompt: "最后确认一下，你能给我的最大方案是什么？",
        preferredTags: ["policy", "supervisor", "reject"],
        riskyTags: ["compensation", "template"],
        successLine: "行，至少你没乱承诺，我回头自己看规则。",
        neutralLine: "那我先这样吧，但体验一般。",
        failureLine: "你这个补偿太随意了，我要找更高级的人。",
        resolveAfter: true,
      },
    ],
  },
  {
    id: "policy-checker-001",
    name: "陈女士",
    handle: "条款逐字看的陈女士",
    type: "policy_checker",
    issue: "会员价保申请被拒，要求解释规则依据。",
    opening: "我看了你们的价保说明，页面写得很清楚。为什么我的申请被系统驳回？",
    initialMetrics: {
      satisfaction: 45,
      anger: 50,
    },
    patience: 68,
    profileNotes: ["重视规则依据", "讨厌随口补偿", "会追问前后一致性"],
    rounds: [
      {
        id: "policy-r1",
        prompt: "别先道歉，你先告诉我系统按哪条规则驳回。",
        preferredTags: ["policy", "investigate"],
        riskyTags: ["template", "compensation"],
        successLine: "好，你先按规则和订单节点核一下。",
        neutralLine: "你可以查，但我要的是能对上的规则。",
        failureLine: "你这不是解释规则，是在糊弄我。",
      },
      {
        id: "policy-r2",
        prompt: "我下单后 24 小时内降价，为什么不算价保？",
        preferredTags: ["policy", "refund_check"],
        riskyTags: ["template", "compensation"],
        successLine: "如果是因为活动类型不在价保范围，你把依据发我。",
        neutralLine: "规则我能接受，但你得说完整。",
        failureLine: "不要给券转移话题，我要知道系统为什么拒。",
      },
      {
        id: "policy-r3",
        prompt: "最后给我一个明确结论：能不能复核，按什么依据？",
        preferredTags: ["policy", "supervisor", "investigate"],
        riskyTags: ["template", "compensation"],
        successLine: "可以，有复核依据和反馈时间我就等结果。",
        neutralLine: "我先接受，但你们后面别换说法。",
        failureLine: "规则说不清楚，我会要求平台介入。",
        resolveAfter: true,
      },
    ],
  },
  {
    id: "passive-aggressive-001",
    name: "周先生",
    handle: "说没事但句句有事的周先生",
    type: "passive_aggressive",
    issue: "安装服务迟到，客户表面克制但非常不满。",
    opening: "没关系，我也就请了一下午假等师傅。你们忙，我懂。",
    initialMetrics: {
      satisfaction: 31,
      anger: 64,
    },
    patience: 52,
    profileNotes: ["表面克制", "需要被认真对待", "模板回复会迅速激怒"],
    rounds: [
      {
        id: "passive-r1",
        prompt: "我不生气，真的。只是家里老人晚上还等着用。",
        preferredTags: ["empathy", "apology", "investigate"],
        riskyTags: ["template", "reject"],
        successLine: "你这么说我舒服一点，至少不是让我自己消化。",
        neutralLine: "行，那你先查一下师傅到底在哪。",
        failureLine: "还是这套话，那我也只能按差评流程走了。",
      },
      {
        id: "passive-r2",
        prompt: "师傅如果今天来不了，你们是不是也只会说抱歉？",
        preferredTags: ["logistics", "investigate", "supervisor"],
        riskyTags: ["template", "reject"],
        successLine: "能确认时间和备选方案就行，我要的是有人负责。",
        neutralLine: "你先问清楚，我不想再等一个空消息。",
        failureLine: "那我知道了，反正浪费时间的是我。",
      },
      {
        id: "passive-r3",
        prompt: "所以今天有没有一个靠谱安排？",
        preferredTags: ["supervisor", "empathy", "policy"],
        riskyTags: ["template", "reject"],
        successLine: "可以，你给明确回访和升级安排，我先配合。",
        neutralLine: "我先记下这个安排，希望别再让我等。",
        failureLine: "行吧，你们继续忙，我去写评价。",
        resolveAfter: true,
      },
    ],
  },
  {
    id: "hair-trigger-001",
    name: "吴先生",
    handle: "随时要投诉的吴先生",
    type: "angry_refund",
    issue: "刚签收的商品包装破损，怀疑是二手货，要求立刻退款并索赔。",
    opening: "你们发的什么东西？包装全烂了，这是二手货吧！我现在就要投诉，给我退款！",
    initialMetrics: {
      satisfaction: 18,
      anger: 92,
    },
    patience: 20,
    profileNotes: ["极高怒气", "容忍度极低", "一句模板就暴走", "需要极速响应"],
    rounds: [
      {
        id: "trigger-r1",
        prompt: "你别说抱歉没用，我要的是处理方案！",
        preferredTags: ["apology", "investigate", "refund_check"],
        riskyTags: ["template", "policy", "reject"],
        successLine: "好，你快点查，我等你一分钟。",
        neutralLine: "那你查，但我计时了。",
        failureLine: "说话就是废话，我现在发12315了。",
      },
      {
        id: "trigger-r2",
        prompt: "查出来了吗？你们到底发的什么？",
        preferredTags: ["refund_check", "supervisor"],
        riskyTags: ["template", "compensation", "reject"],
        successLine: "能升级处理就先这样，但你得给我时间节点。",
        neutralLine: "那行，但你得盯着，别让我再追。",
        failureLine: "给券？我要的是赔偿！你叫你主管来！",
        resolveAfter: true,
      },
    ],
  },
  {
    id: "easygoing-001",
    name: "方女士",
    handle: "超好说话的方女士",
    type: "lost_package",
    issue: "包裹迟到三天，但态度温和，愿意等待合理解释。",
    opening: "不好意思打扰你，我的包裹好像有点延误，方便帮我查一下吗？不急的。",
    initialMetrics: {
      satisfaction: 72,
      anger: 18,
    },
    patience: 92,
    profileNotes: ["极高耐心", "态度温和", "欣赏真诚回应", "过度敷衍反而会失望"],
    rounds: [
      {
        id: "easy-r1",
        prompt: "我看物流好像卡在中转站了，是正常情况吗？",
        preferredTags: ["logistics", "investigate"],
        riskyTags: ["template"],
        successLine: "谢谢你帮我查，有这个信息就安心多了。",
        neutralLine: "好的，我再等等看。",
        failureLine: "嗯……那我自己再看看吧。",
      },
      {
        id: "easy-r2",
        prompt: "如果再等两天还没到，你们怎么处理？",
        preferredTags: ["policy", "logistics", "investigate"],
        riskyTags: ["template", "reject"],
        successLine: "有这个保障流程就很好，我放心了。",
        neutralLine: "好，我记下来了，谢谢。",
        failureLine: "哦……那我再等等看吧，希望能到。",
        resolveAfter: true,
      },
    ],
  },
];
